import "../public/assets/css/style.css";
import "../public/assets/css/bootstrap.min.css";
import "../public/assets/css/fontawesome.min.css";
import "../public/assets/css/slick.css";
// import "../public/assets/css/slick-theme.css";
// import "../public/assets/js/slick";
// import "../public/assets/js/jquery-3.6.4";
// import "../public/assets/js/custom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";
import React from "react";
import Script from "next/script";

export default function App({ Component, pageProps }) {
  return (
    <div className="container-box">
      <Head>
        <title>Food App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* FONT AWESOME */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        />

        <link
          href="https://fonts.googleapis.com/css2?family=Poppins"
          rel="stylesheet"
        ></link>
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Montserrat"
          rel="stylesheet"
        ></link> */}

        {/* FAVICON */}
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/assets/images/favicon/assets/images/favicon/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/assets/images/favicon/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/assets/images/favicon/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/assets/images/favicon/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/assets/images/favicon/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/assets/images/favicon/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/assets/images/favicon/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/assets/images/favicon/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/assets/images/favicon/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/assets/images/favicon/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/assets/images/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/assets/images/favicon/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/assets/images/favicon/favicon-16x16.png"
        ></link>
        <link rel="icon" href="/assets/images/favicon/favicon.ico" />

        {/* SLICK CSS  */}
        <link rel="stylesheet" href="/assets/css/slick.css" />
        <link rel="stylesheet" href="/assets/css/slick-theme.css" />

        {/* ANIMATE CSS */}

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
        {/*  JQUERY  */}
        <Script
          type="text/javascript"
          src="/assets/js/jquery-3.6.4.js"
        ></Script>
        {/* SLICK JS */}
        <Script
          type="text/javascript"
          src="//code.jquery.com/jquery-1.11.0.min.js"
        ></Script>
        <Script
          type="text/javascript"
          src="//code.jquery.com/jquery-migrate-1.2.1.min.js"
        ></Script>
        <Script type="text/javascript" src="slick/slick.min.js"></Script>

        {/* <!-- CUSTOM JS --> */}
        <Script src="/assets/js/custom.js"></Script>
      </Head>

      <Header />
      <Component {...pageProps} />

      <Footer />
    </div>
  );
}
